ALTER TABLE EMPRESAS
  ADD COLUMN IF NOT EXISTS timbrado       VARCHAR(20) NULL,
  ADD COLUMN IF NOT EXISTS timbrado_vence DATE NULL;

UPDATE EMPRESAS
   SET timbrado = '12557031', timbrado_vence = '2027-12-31'
 WHERE timbrado IS NULL;

ALTER TABLE VENTAS
  ADD COLUMN IF NOT EXISTS anulada         SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS anulada_fecha   DATETIME NULL,
  ADD COLUMN IF NOT EXISTS anulada_usuario VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS anulada_motivo  VARCHAR(200) NULL;

ALTER TABLE CUENTAS_COBRAR
  ADD COLUMN IF NOT EXISTS anulada SMALLINT NOT NULL DEFAULT 0;

ALTER TABLE PLAZOS
  ADD COLUMN IF NOT EXISTS activo SMALLINT NOT NULL DEFAULT 1;

ALTER TABLE DEPOSITOS
  ADD COLUMN IF NOT EXISTS activo SMALLINT NOT NULL DEFAULT 1;

CREATE TABLE IF NOT EXISTS AUDITORIA (
  id       INT NOT NULL AUTO_INCREMENT,
  fecha    DATETIME NOT NULL,
  usuario  VARCHAR(50) NOT NULL,
  accion   VARCHAR(30) NOT NULL,
  tabla    VARCHAR(30) NOT NULL,
  tablaid  INT NOT NULL,
  detalle  VARCHAR(500) NULL,
  CONSTRAINT pkauditoria PRIMARY KEY (id)
);
